# Generated by Django 3.1.2 on 2020-11-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('redirect_link', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='shiv.Tag')),
            ],
        ),
    ]
