# Generated by Django 3.1.2 on 2020-11-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sub_headline',
            new_name='about',
        ),
    ]
